### PR TITLE
add brave search

### LINKED ISSUE #5: Add Brave-Search as a search Engine in the startpage

### PR DESCRIPTION
**Pull request by chrollorifat**

### CODE REVIEW

**Comment by dominichayesferen** [comment]
You need to... add the search engine to the search engines metadata file.

**Review by dominichayesferen — CHANGES_REQUESTED** [review]
You need to add Brave to the search engines file.

**Comment by ChrolloRifat** [comment]
But where is the search engines file?!

**Comment by chrollorifat** [comment]
> You need to add Brave to the search engines file.
@dominichayesferen 
added brave search in the engines file.

**Pull request merged**
